In [2]:
# 代码 1
import numpy as np #导入 NumPy 库
arr1 = np.array([1, 2, 3, 4]) #创建一维数组
print(' 创建的数组为： ',arr1)

# 创建二维数组
arr2 = np.array([[1, 2, 3, 4],[4, 5, 6, 7], [7, 8, 9, 10]])
print('创建的数组为：\n',arr2)

print('数组类型为：',arr2.dtype)  #查看数组类型
print('数组元素个数为：',arr2.size)  #查看数组元素个数
print('数组每个元素大小为：',arr2.itemsize)  #查看数组每个元素大小

 创建的数组为：  [1 2 3 4]
创建的数组为：
 [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
数组类型为： int32
数组元素个数为： 12
数组每个元素大小为： 4
